
##################################
#  Ansible Inventory Definitions #
##################################

switch_box = "cumulus-vx-2.5.7"
host_box = "ubuntu/trusty64"

groups = {
  "spine" => ["spine1", "spine2"],
  "leaf" => ["leaf1", "leaf2", "leaf3", "leaf4"],
  "host" => ["host1", "host2"],
  "vx:children" => ["spine", "leaf"],
  "vagrant:children" => ["spine", "leaf", "host"]
}


##################################
#   Vagrant Machine Definitions  #
##################################

Vagrant.configure(2) do |config|

  config.vm.define "spine1" do |spine1|
	spine1.vm.box = switch_box

    spine1.vm.hostname = "spine1"
    spine1.vm.network "private_network", virtualbox__intnet: "s1l1"
    spine1.vm.network "private_network", virtualbox__intnet: "s1l2"
    spine1.vm.network "private_network", virtualbox__intnet: "s1l3"
    spine1.vm.network "private_network", virtualbox__intnet: "s1l4"
    spine1.vm.network "private_network", virtualbox__intnet: "s1s2"

    spine1.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    spine1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111111"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end

  end

  config.vm.define "spine2" do |spine2|
	spine2.vm.box = switch_box

    spine2.vm.hostname = "spine2"
    spine2.vm.network "private_network", virtualbox__intnet: "s2l1"
    spine2.vm.network "private_network", virtualbox__intnet: "s2l2"
    spine2.vm.network "private_network", virtualbox__intnet: "s2l3"
    spine2.vm.network "private_network", virtualbox__intnet: "s2l4"
    spine2.vm.network "private_network", virtualbox__intnet: "s1s2"

    spine2.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    spine2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111112"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "leaf1" do |leaf1|
	leaf1.vm.box = switch_box

    leaf1.vm.hostname = "leaf1"
    leaf1.vm.network "private_network", virtualbox__intnet: "s1l1"
    leaf1.vm.network "private_network", virtualbox__intnet: "s2l1"
    leaf1.vm.network "private_network", virtualbox__intnet: "l1l2"
    leaf1.vm.network "private_network", virtualbox__intnet: "l1h1"

    leaf1.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    leaf1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111121"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
    end

  end

  config.vm.define "leaf2" do |leaf2|
	leaf2.vm.box = switch_box

    leaf2.vm.hostname = "leaf2"
    leaf2.vm.network "private_network", virtualbox__intnet: "s1l2"
    leaf2.vm.network "private_network", virtualbox__intnet: "s2l2"
    leaf2.vm.network "private_network", virtualbox__intnet: "l1l2"
    leaf2.vm.network "private_network", virtualbox__intnet: "l2h1"

    leaf2.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    leaf2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111122"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
    end

  end

  config.vm.define "leaf3" do |leaf3|
	leaf3.vm.box = switch_box

    leaf3.vm.hostname = "leaf3"
    leaf3.vm.network "private_network", virtualbox__intnet: "s1l3"
    leaf3.vm.network "private_network", virtualbox__intnet: "s2l3"
    leaf3.vm.network "private_network", virtualbox__intnet: "l3l4"
    leaf3.vm.network "private_network", virtualbox__intnet: "l3h2"

    leaf3.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    leaf3.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111123"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
    end

  end

  config.vm.define "leaf4" do |leaf4|
	leaf4.vm.box = switch_box

    leaf4.vm.hostname = "leaf4"
    leaf4.vm.network "private_network", virtualbox__intnet: "s1l4"
    leaf4.vm.network "private_network", virtualbox__intnet: "s2l4"
    leaf4.vm.network "private_network", virtualbox__intnet: "l3l4"
    leaf4.vm.network "private_network", virtualbox__intnet: "l4h2"

    leaf4.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/switch-provision.yml"
      ansible.groups = groups
    end

    leaf4.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111124"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
    end

  end

  config.vm.define "host1" do |host1|
	host1.vm.box = host_box

    host1.vm.hostname = "host1"
    host1.vm.network "private_network", virtualbox__intnet: "l1h1", auto_config: false
    host1.vm.network "private_network", virtualbox__intnet: "l2h1", auto_config: false

    host1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111131"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end

    host1.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/host-provision.yml"
      ansible.groups = groups
    end

  end

  config.vm.define "host2" do |host2|
	host2.vm.box = host_box

    host2.vm.hostname = "host2"
    host2.vm.network "private_network", virtualbox__intnet: "l3h2", auto_config: false
    host2.vm.network "private_network", virtualbox__intnet: "l4h2", auto_config: false

    host2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--macaddress1", "000000111132"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end

    host2.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/host-provision.yml"
      ansible.groups = groups
    end

  end
end
