---
- hosts: all
  roles:
    - host
    - common
  user: vagrant
  become: yes
  tasks:
    - name: configure /etc/motd
      template: src=motd.j2 dest=/etc/motd
    - name: install ifenslave
      apt: name=ifenslave state=present
    - name: install vlan
      apt: name=vlan state=present
    - name: install vim
      apt: name=vim state=present
    - name: adding bonding and rtc modules to /etc/modules
      lineinfile: dest=/etc/modules line="{{ item }}"
      with_items:
        - "rtc"
        - "bonding"
        - "8021q"
    - name: push hypervisors public SSH key
      # If Linux
      # authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      #
      # If Mac
      authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    # /usr/local/bin
    - name: Check that usr/local/bin directory exists
      become: false
      local_action: stat path=roles/host/files/usr/local/bin/
      register: stat_result
    - name: copy /usr/local/bin directory
      when: stat_result.stat.exists == True
      copy: src=roles/host/files/usr/local/bin/ dest=/usr/local/bin/ owner=root group=staff mode="u+rwx,g+rx,o+rx"
    # .alias
    - name: check that alias file exists
      become: false
      local_action: stat path=roles/host/files/root/alias
      register: stat_result
    - name: copy .alias file
      when: stat_result.stat.exists == True
      copy: src=roles/host/files/root/alias dest=/root/.alias
    # .bashrc
    - name: check that bashrc file exists
      become: false
      local_action: stat path=roles/host/files/root/bashrc
      register: stat_result
    - name: copy .bashrc file
      when: stat_result.stat.exists == True
      copy: src=roles/host/files/root/bashrc dest=/root/.bashrc
    # .profile
    - name: check that profile file exists
      become: false
      local_action: stat path=roles/host/files/root/profile
      register: stat_result
    - name: copy .profile file
      when: stat_result.stat.exists == True
      copy: src=roles/host/files/root/profile dest=/root/.profile
